name: End-to-end tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Run Cypress E2E tests
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Start Server
        run: npm start

      - name: Run Cypress Tests
        run: cypress run
        with:
          wait-on: "http://localhost:3000"
