# Copied from https://github.com/cypress-io/github-action?tab=readme-ov-file#artifacts

name: End-to-end tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Run Cypress E2E tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install Node.js dependencies
        run: npm ci
      - uses: cypress-io/github-action@v6
        env:
          DEBUG: "cypress:*"
        with:
          build: npm run build --if-present
          start: npm start
          wait-on: "https://localhost:3000/"
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
